name: Snake

on:
  schedule:
    - cron: "0 */12 * * *"     # every 12h
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # allow pushing a branch
    steps:
      - uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Lousd1
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B output
          git add dist/
          git commit -m "update snake" || true
          git push -f origin output
